//BMF100   JOB (ACCT,BMF),'COMBINED ANNUAL WAGE',CLASS=A,
//             MSGCLASS=X,MSGLEVEL=(1,1),REGION=4096K,
//             NOTIFY=&SYSUID
//*
//* STEP 100 - COMBINED ANNUAL WAGE REPORTING MATCH
//* MEMBER MAINTAINED BY RUN CONTROL. DO NOT EDIT IN PLACE.
//*
//JOBLIB   DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//*
//* ---- PRESORT MODULE MASTER TO MERGE SEQUENCE
//SRT1     EXEC PGM=SORT,COND=(4,LT)
//SORTIN   DD DSN=TAX.BMF.MODULE.OFF(0),
//             DISP=SHR
//SORTOUT  DD DSN=&&MODSEQ,DISP=(NEW,PASS),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0)
//SYSIN    DD DSN=TAX.BMF.CTLLIB(MODSRT),DISP=SHR
//SORTWK01 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK02 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK03 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK04 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SYSOUT   DD SYSOUT=*
//*
//* ---- PRESORT SSA W-2 TOTALS TO MERGE SEQUENCE
//SRT2     EXEC PGM=SORT,COND=(4,LT)
//SORTIN   DD DSN=TAX.SSA.W2.TOTALS,
//             DISP=SHR
//SORTOUT  DD DSN=&&W2SEQ,DISP=(NEW,PASS),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=044,BLKSIZE=0)
//SYSIN    DD DSN=TAX.BMF.CTLLIB(W2SRT),DISP=SHR
//SORTWK01 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK02 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SYSOUT   DD SYSOUT=*
//*
//CAWRMTCH EXEC PGM=CAWRMTCH,COND=(4,LT)
//STEPLIB  DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//MODIN    DD DSN=&&MODSEQ,DISP=(OLD,DELETE)
//W2IN     DD DSN=&&W2SEQ,DISP=(OLD,DELETE)
//CWRPT    DD DSN=TAX.BMF.CAWR.LIST,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=133,BLKSIZE=0)
//SYSOUT   DD SYSOUT=*
//SYSUDUMP DD SYSOUT=D
//*
