//BMF100   JOB (ACCT,BMF),'COMBINED ANNUAL WAGE',CLASS=A,
//             MSGCLASS=X,MSGLEVEL=(1,1),REGION=4096K,
//             NOTIFY=&SYSUID
//*
//* STEP 100 - COMBINED ANNUAL WAGE REPORTING MATCH
//* MEMBER MAINTAINED BY RUN CONTROL. DO NOT EDIT IN PLACE.
//*
//JOBLIB   DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//*
//CAWRMTCH EXEC PGM=CAWRMTCH,COND=(4,LT)
//STEPLIB  DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//MODIN    DD DSN=TAX.BMF.MODULE.OFF(0),
//             DISP=SHR
//W2IN     DD DSN=TAX.SSA.W2.TOTALS,
//             DISP=SHR
//CWRPT    DD DSN=TAX.BMF.CAWR.LIST,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=133,BLKSIZE=0)
//SYSOUT   DD SYSOUT=*
//SYSUDUMP DD SYSOUT=D
//*
