//BMF020   JOB (ACCT,BMF),'DUPLICATE FILING CON',CLASS=A,
//             MSGCLASS=X,MSGLEVEL=(1,1),REGION=4096K,
//             NOTIFY=&SYSUID
//*
//* STEP 020 - DUPLICATE FILING CONDITION
//* MEMBER MAINTAINED BY RUN CONTROL. DO NOT EDIT IN PLACE.
//*
//JOBLIB   DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//*
//* ---- PRESORT MODULE MASTER TO MERGE SEQUENCE
//SRT1     EXEC PGM=SORT,COND=(4,LT)
//SORTIN   DD DSN=TAX.BMF.MODULE(0),
//             DISP=SHR
//SORTOUT  DD DSN=&&MODSEQ,DISP=(NEW,PASS),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0)
//SYSIN    DD DSN=TAX.BMF.CTLLIB(MODSRT),DISP=SHR
//SORTWK01 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK02 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK03 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK04 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SYSOUT   DD SYSOUT=*
//*
//* ---- PRESORT TRANSACTION FILE TO MERGE SEQUENCE
//SRT2     EXEC PGM=SORT,COND=(4,LT)
//SORTIN   DD DSN=TAX.BMF.TRANS(0),
//             DISP=SHR
//SORTOUT  DD DSN=&&TRNSEQ,DISP=(NEW,PASS),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=080,BLKSIZE=0)
//SYSIN    DD DSN=TAX.BMF.CTLLIB(TRNSRT),DISP=SHR
//SORTWK01 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK02 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK03 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK04 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SYSOUT   DD SYSOUT=*
//*
//DUPCHK   EXEC PGM=DUPCHK,COND=(4,LT)
//STEPLIB  DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//MODIN    DD DSN=&&MODSEQ,DISP=(OLD,DELETE)
//TRNIN    DD DSN=&&TRNSEQ,DISP=(OLD,DELETE)
//MODOT    DD DSN=TAX.BMF.MODULE.DUP(+1),
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0)
//DUPRPT   DD DSN=TAX.BMF.DUPCHK.REJECTS(+1),
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=133,BLKSIZE=0)
//SYSOUT   DD SYSOUT=*
//SYSUDUMP DD SYSOUT=D
//*
