//BMF010   JOB (ACCT,BMF),'BMF ENTITY VALIDATIO',CLASS=A,
//             MSGCLASS=X,MSGLEVEL=(1,1),REGION=4096K,
//             NOTIFY=&SYSUID
//*
//* STEP 010 - BMF ENTITY VALIDATION
//* MEMBER MAINTAINED BY RUN CONTROL. DO NOT EDIT IN PLACE.
//*
//JOBLIB   DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//*
//* ---- PRESORT ENTITY MASTER TO EIN SEQUENCE
//SRT1     EXEC PGM=SORT,COND=(4,LT)
//SORTIN   DD DSN=TAX.BMF.ENTITY.MASTER,
//             DISP=SHR
//SORTOUT  DD DSN=&&ENTSEQ,DISP=(NEW,PASS),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0)
//SYSIN    DD DSN=TAX.BMF.CTLLIB(ENTSRT),DISP=SHR
//SORTWK01 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SORTWK02 DD UNIT=SYSDA,SPACE=(CYL,(20,5))
//SYSOUT   DD SYSOUT=*
//*
//ENTVAL   EXEC PGM=ENTVAL,COND=(4,LT)
//STEPLIB  DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//ENTIN    DD DSN=&&ENTSEQ,DISP=(OLD,DELETE)
//ENTOT    DD DSN=TAX.BMF.ENTITY.VALID(+1),
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0)
//ERRPT    DD DSN=TAX.BMF.ENTVAL.REJECTS(+1),
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=133,BLKSIZE=0)
//SYSOUT   DD SYSOUT=*
//SYSUDUMP DD SYSOUT=D
//*
