//BMF040   JOB (ACCT,BMF),'FAILURE TO DEPOSIT P',CLASS=A,
//             MSGCLASS=X,MSGLEVEL=(1,1),REGION=4096K,
//             NOTIFY=&SYSUID
//*
//* STEP 040 - FAILURE TO DEPOSIT PENALTY
//* MEMBER MAINTAINED BY RUN CONTROL. DO NOT EDIT IN PLACE.
//*
//JOBLIB   DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//*
//FTDCALC  EXEC PGM=FTDCALC,COND=(4,LT)
//STEPLIB  DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//MODIN    DD DSN=TAX.BMF.MODULE.STAT(0),
//             DISP=SHR
//TRNIN    DD DSN=TAX.BMF.TRANS(0),
//             DISP=SHR
//MODOT    DD DSN=TAX.BMF.MODULE.FTD(+1),
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0)
//FTRPT    DD DSN=TAX.BMF.FTDCALC.LIST,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=133,BLKSIZE=0)
//SYSOUT   DD SYSOUT=*
//SYSUDUMP DD SYSOUT=D
//*
