//BMF110   JOB (ACCT,BMF),'NOTICE SELECTION AND',CLASS=A,
//             MSGCLASS=X,MSGLEVEL=(1,1),REGION=4096K,
//             NOTIFY=&SYSUID
//*
//* STEP 110 - NOTICE SELECTION AND GENERATION
//* MEMBER MAINTAINED BY RUN CONTROL. DO NOT EDIT IN PLACE.
//*
//JOBLIB   DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//*
//NOTGEN   EXEC PGM=NOTGEN,COND=(4,LT)
//STEPLIB  DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//MODIN    DD DSN=TAX.BMF.MODULE.OFF(0),
//             DISP=SHR
//NOTOT    DD DSN=TAX.BMF.NOTICE(+1),
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=100,BLKSIZE=0)
//NGRPT    DD DSN=TAX.BMF.NOTGEN.LIST,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=133,BLKSIZE=0)
//SYSOUT   DD SYSOUT=*
//SYSUDUMP DD SYSOUT=D
//*
