//BMF030   JOB (ACCT,BMF),'STATUTE DATE COMPUTA',CLASS=A,
//             MSGCLASS=X,MSGLEVEL=(1,1),REGION=4096K,
//             NOTIFY=&SYSUID
//*
//* STEP 030 - STATUTE DATE COMPUTATION
//* MEMBER MAINTAINED BY RUN CONTROL. DO NOT EDIT IN PLACE.
//*
//JOBLIB   DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//*
//STATCALC EXEC PGM=STATCALC,COND=(4,LT)
//STEPLIB  DD DSN=TAX.BMF.LOADLIB,DISP=SHR
//MODIN    DD DSN=TAX.BMF.MODULE.DUP(0),
//             DISP=SHR
//MODOT    DD DSN=TAX.BMF.MODULE.STAT(+1),
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0)
//STRPT    DD DSN=TAX.BMF.STATCALC.LIST,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(CYL,(50,10),RLSE),
//             DCB=(RECFM=FB,LRECL=133,BLKSIZE=0)
//SYSOUT   DD SYSOUT=*
//SYSUDUMP DD SYSOUT=D
//*
